import { Outfit } from "next/font/google";
import "./globals.css";
// import { ClerkProvider } from "@clerk/nextjs";
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs'

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
});



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body
        className={`${outfit.variable}  antialiased`}
      >
        {children}
      </body>
    </html>
    </ClerkProvider>
  );
}
